// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbP6-_vJJtYatyRK7eBN9Hh8BEta2OjNM',
    appId: '1:88115024354:web:05117106448552ebc529bb',
    messagingSenderId: '88115024354',
    projectId: 'crafto-copy',
    authDomain: 'crafto-copy.firebaseapp.com',
    storageBucket: 'crafto-copy.appspot.com',
    measurementId: 'G-26WB39F6TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRe4llB6VNKMDklUCFS0FXguDnE9zL7HA',
    appId: '1:88115024354:android:f04db9071b6f91b6c529bb',
    messagingSenderId: '88115024354',
    projectId: 'crafto-copy',
    storageBucket: 'crafto-copy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvI5bokABiwz3Upx39vPuE_vj_5NOc9BI',
    appId: '1:88115024354:ios:c8d7d8e0b2fa7f00c529bb',
    messagingSenderId: '88115024354',
    projectId: 'crafto-copy',
    storageBucket: 'crafto-copy.appspot.com',
    iosBundleId: 'com.example.picPoster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvI5bokABiwz3Upx39vPuE_vj_5NOc9BI',
    appId: '1:88115024354:ios:c8d7d8e0b2fa7f00c529bb',
    messagingSenderId: '88115024354',
    projectId: 'crafto-copy',
    storageBucket: 'crafto-copy.appspot.com',
    iosBundleId: 'com.example.picPoster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbP6-_vJJtYatyRK7eBN9Hh8BEta2OjNM',
    appId: '1:88115024354:web:ebc16e463b626009c529bb',
    messagingSenderId: '88115024354',
    projectId: 'crafto-copy',
    authDomain: 'crafto-copy.firebaseapp.com',
    storageBucket: 'crafto-copy.appspot.com',
    measurementId: 'G-HPTCBGVR9Y',
  );
}
